name: Wiki Archive Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-wiki-archive:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper updates
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'  # Enable pip cache
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python*/site-packages
          wiki_articles/  # Cache the articles directory
          archive_progress.json  # Cache the progress file
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-articles-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-articles-
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-
          ${{ runner.os }}-pip-
    
    - name: Configure Git
      run: |
        git config --global user.name "zaidhafeeez"
        git config --global user.email "188496560+zaidhafeeez@users.noreply.github.com"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Wiki Archive Script
      run: python script.py
    
    - name: Check for changes
      id: check_changes
      run: |
        if [[ -n "$(git status --porcelain wiki_articles/)" ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if there are changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        # Stage only the wiki_articles directory
        git add wiki_articles/

        # Get the current date for the commit message
        current_date=$(date +'%Y-%m-%d')
        
        # Create commit with meaningful message
        git commit -m "Update wiki articles - $current_date" \
                  -m "Automated update of Wikipedia articles" \
                  -m "Category: Python (programming language)"
        
        # Push changes
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
